apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testxsxs-etcd-1660630851-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: hostpath
  volumeMode: Filesystem
